# Generated by Django 5.0.6 on 2024-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_computer_science_and_engineering_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compurter_science_and_engineering',
            fields=[
                ('student_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Computer_science_and_engineering',
        ),
        migrations.RemoveField(
            model_name='information_science_and_engineering',
            name='address',
        ),
    ]
