# Generated by Django 5.0.6 on 2024-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_and_engineering',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='information_science_and_engineering',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
