# Generated by Django 5.0.6 on 2024-07-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_compurter_science_and_engineering_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compurter_science_and_engineering',
            new_name='Computer_science_and_engineering',
        ),
    ]
