# Generated by Django 5.0.6 on 2024-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_rename_compurter_science_and_engineering_computer_science_and_engineering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BinaryField()),
            ],
        ),
    ]
