# Generated by Django 5.0.6 on 2024-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_fees_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_details',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
